const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Behaviors.Rotate,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Text.Acts.AddInstanceVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Behaviors.Platform.Acts.SetJumpStrength,
		C3.Plugins.TiledBg.Acts.RotateCounterclockwise,
		C3.Plugins.TiledBg.Acts.RotateClockwise,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.solid.Acts.SetEnabled
	];
};
self.C3_JsPropNameTable = [
	{Platform: 0},
	{ScrollTo: 0},
	{Player: 0},
	{Solid: 0},
	{Platforms: 0},
	{Rotate: 0},
	{Tomato: 0},
	{Keyboard: 0},
	{Lava: 0},
	{secretPlatform: 0},
	{void: 0},
	{key: 0},
	{key2: 0},
	{GoldenTomato: 0},
	{Portal: 0},
	{Jumpchanger: 0},
	{wall: 0},
	{wallmover: 0},
	{bars: 0},
	{door: 0},
	{barrier: 0},
	{escape: 0},
	{button: 0},
	{button2: 0},
	{button3: 0},
	{button4: 0},
	{jump: 0},
	{images: 0},
	{arrow: 0},
	{Score: 0},
	{cookie: 0},
	{block: 0}
];

self.InstanceType = {
	Player: class extends self.ISpriteInstance {},
	Platforms: class extends self.ITiledBackgroundInstance {},
	Tomato: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Lava: class extends self.ITiledBackgroundInstance {},
	secretPlatform: class extends self.ITiledBackgroundInstance {},
	void: class extends self.ITiledBackgroundInstance {},
	key: class extends self.ITiledBackgroundInstance {},
	key2: class extends self.ITiledBackgroundInstance {},
	GoldenTomato: class extends self.ISpriteInstance {},
	Portal: class extends self.ISpriteInstance {},
	Jumpchanger: class extends self.ITiledBackgroundInstance {},
	wall: class extends self.ITiledBackgroundInstance {},
	wallmover: class extends self.ITiledBackgroundInstance {},
	bars: class extends self.ISpriteInstance {},
	door: class extends self.ITiledBackgroundInstance {},
	barrier: class extends self.ITiledBackgroundInstance {},
	escape: class extends self.ISpriteInstance {},
	button: class extends self.ISpriteInstance {},
	button2: class extends self.ISpriteInstance {},
	button3: class extends self.ISpriteInstance {},
	button4: class extends self.ISpriteInstance {},
	jump: class extends self.ITiledBackgroundInstance {},
	images: class extends self.ISpriteInstance {},
	arrow: class extends self.ISpriteInstance {},
	Score: class extends self.ITextInstance {},
	cookie: class extends self.ISpriteInstance {},
	block: class extends self.ITiledBackgroundInstance {}
}